### PR TITLE
Adding "scroll-target" option

### PR DESCRIPTION
**Pull request by dlhdesign**
Adding a simple string attribute for targeting the scrolling element. Defaults to $document.

### CODE REVIEW

**Comment by oblador** [comment]
Doesn't this introduce a jQuery dependency?

**Comment by dlhdesign** [comment]
jQuery (or a "jQuery light" version, at least) is already part of Angular. There are no special requirements to use it in this fashion.

**Comment by oblador** [comment]
jqLite doesn't support general CSS selectors like jQuery does and you are depending on the window global `$` (thinking of [this line](https://github.com/oblador/angular-parallax/pull/25/files#diff-ed23370648a3059e708c78cdca3d6bbeR75)) which is not available without jQuery. In angular all dependencies should be injected and not depend on globals. 

It's a good functionality you're adding, thanks :+1: – but I'm not comfortable adding a jQuery dependency. If you could refactor I'd be happy to merge.

**Comment by oblador** [comment]
Also please reverse bumping version numbers/js builds and squash commits, then I'm happy :smile:

**Comment by dlhdesign** [comment]
As always for Angular, `$` is available (in it's limited fashion, granted) as a global. If the developer wants to extend the available functionality (to get complex CSS selectors, for example), they can choose to include a full version of jQuery. But there is no forced dependency on it.

I appreciate your efforts on this, but I don't have the inclination nor time to modify this library further as these changes suit the needs of my client. Best of luck and thanks again for your work.

**Pull request closed without merging**
